### ISSUE TITLE
Package update to build185: mariadb and mariadb-server-galera

### ISSUE THREAD

**Issue by jackiehjm** [Wind-River/meta-akraino#16]
It is required in:
https://gerrit.akraino.org/r/gitweb?p=ta/manifest.git;a=blob_plain;f=packages.yaml;hb=HEAD

In build185:
[newadmin@controller-1 ~]$ rpm -ql mariadb-server-galera-10.1.20-2.el7.x86_64
/etc/my.cnf.d/galera.cnf
/etc/sysconfig/clustercheck
/usr/bin/clustercheck
/usr/bin/galera_new_cluster
/usr/bin/galera_recovery
/usr/share/doc/mariadb-server-galera-10.1.20
/usr/share/doc/mariadb-server-galera-10.1.20/README.wsrep
/usr/share/licenses/mariadb-server-galera-10.1.20
/usr/share/licenses/mariadb-server-galera-10.1.20/LICENSE.clustercheck
/usr/share/mariadb/systemd/use_galera_new_cluster.conf
/usr/share/selinux/packages/mariadb/mariadb-server-galera.pp

**Comment by gaolitao** [comment]
According to the notes from website, it seems that if we use MariaDB 10.1, MariaDB-Galera-server is not needed here. 

Need to confirm the version of the MariaDB  being used in Akraino.

@jackiehjm 

```
If  you are using the 10.0, you would need MariaDB-Galera-server package compared to 10.1 where you just need MariaDB-server.

There are no longer separate MariaDB Galera Cluster releases for MariaDB 10.1 and above. Simply download MariaDB (10.1 or above) and configure your cluster as normal. MariaDB-10.1 is just ‘Galera ready’.

The galera package will provide you the /usr/lib64/galera/libgalera_smm.so  and several binaries for the cluster configuration. 
```

**Comment by gaolitao** [comment]
According to the notes from website, it seems that if we use MariaDB 10.1, MariaDB-Galera-server is not needed here. 

Need to confirm the version of the MariaDB  being used in Akraino.

@jackiehjm 

```
If  you are using the 10.0, you would need MariaDB-Galera-server package compared to 10.1 where you just need MariaDB-server.

There are no longer separate MariaDB Galera Cluster releases for MariaDB 10.1 and above. Simply download MariaDB (10.1 or above) and configure your cluster as normal. MariaDB-10.1 is just ‘Galera ready’.

The galera package will provide you the /usr/lib64/galera/libgalera_smm.so  and several binaries for the cluster configuration. 
```

**Comment by jackiehjm** [comment]
@gaolitao In Akraino build 185:
[root@controller-1 ~]# rpm -qa|grep mariadb
mariadb-10.1.20-2.el7.x86_64
mariadb-errmsg-10.1.20-2.el7.x86_64
mariadb-server-10.1.20-2.el7.x86_64
mariadb-server-galera-10.1.20-2.el7.x86_64
mariadb-config-10.1.20-2.el7.x86_64
mariadb-common-10.1.20-2.el7.x86_64
mariadb-libs-10.1.20-2.el7.x86_64
mariadb-devel-10.1.20-2.el7.x86_64

**Comment by gaolitao** [comment]
> @gaolitao In Akraino build 185:
> [root@controller-1 ~]# rpm -qa|grep mariadb
> mariadb-10.1.20-2.el7.x86_64
> mariadb-errmsg-10.1.20-2.el7.x86_64
> mariadb-server-10.1.20-2.el7.x86_64
> mariadb-server-galera-10.1.20-2.el7.x86_64
> mariadb-config-10.1.20-2.el7.x86_64
> mariadb-common-10.1.20-2.el7.x86_64
> mariadb-libs-10.1.20-2.el7.x86_64
> mariadb-devel-10.1.20-2.el7.x86_64

So, all other mariadb pkgs except mariadb-server-galera have been ported?

**Comment by jackiehjm** [comment]
yes, although the version and packages split is different, but all other pkgs except mariadb-server-galera have been included.

**Comment by gaolitao** [comment]
> yes, although the version and packages split is different, but all other pkgs except mariadb-server-galera have been included.

Are you referring to src_wrl1018/layers/meta-openembedded/meta-oe/recipes-dbs/mysql/mariadb_5.5.61.bb?

Given the expected version is 10.1.20, is 5.5.61 too old?
