### ISSUE TITLE
"PasswordAuthentication yes"  should be set in sshd_config 

### ISSUE THREAD

**Issue by gaolitao** [Wind-River/meta-akraino#58]
If this option is set to 'no', there will be following ssh login issue from outside:

```
uschwager@tarzan:~$ ssh root@147.11.89.11
Permission denied (publickey).
```

**Comment by gaolitao** [comment]
issue is still observed, and the PasswordAuthentication is still 'no'

**Comment by jackiehjm** [comment]
Cloud-init set it back to 'no'
